### ISSUE TITLE
ローカル環境でも簡単に動かせるようにする

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary.github.io#11]
mongodbとmemcachedに依存しているので、開発中にローカル環境で動かすのが少し面倒。
1. GemfileとtDiary.confを書き換えて、ローカルではdefault ioを使う
2. dockerを使う
3. heroku-dockerを使う

**Comment by tdtds** [comment]
4. Heroku pipelineを使うことでローカルに実行環境を持たない (←最近これをよくやる)
