### ISSUE TITLE
blogデータのバックアップ

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary.github.io#7]
mongolabに保存している日記データのバックアップをとる方法を考える。

**Comment by tdtds** [comment]
tDiary.Netではこんな感じのスクリプトを毎日回してます(3日分保存):

```
mongo_tools -B hoge "`heroku config:get MONGODB_URI -a hoge`"
find . -name '??????????????' -type d -ctime +2 | xargs rm -rf
```

`mongo_tools`は[これ](https://github.com/tdtds/massr/blob/master/bin/mongo_tools.sh)

**Comment by tdtds** [comment]
GitHub pages化したので close
